name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports: ['5433:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # Check out main instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
          
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1
          
      # - name: Gigalixir Action
      #   uses: mhanberg/gigalixir-action@v0.4.0
      #   with:
      #     GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP_NAME }}
      #     GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
      #     GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
      #     MIGRATIONS: true
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Gigalixir CLI Install
        run: sudo pip install gigalixir --ignore-installed six
      - name: Gigalixir Login
        run: gigalixir login -e "${{ secrets.GIGALIXIR_USERNAME }}" -y -p "${{ secrets.GIGALIXIR_PASSWORD }}"
      - name: Gigalixir Git Remote
        run: gigalixir git:remote ${{ secrets.GIGALIXIR_APP_NAME }}
      - name: Gigalixir Push
        run: git push -f gigalixir HEAD:refs/heads/master
      - name: Gigalixir Run Migration
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: gigalixir ps:migrate -a ${{ secrets.GIGALIXIR_APP_NAME }}

